### ISSUE TITLE
Finish implementing IR parser

### ISSUE THREAD

**Issue by dubiousconst282** [dubiousconst282/DistIL#2]
## TODOs
- [x] Core
  - [x] Lexer
  - [x] AST and parser
    - [x] Type parser
      - [x] Nested types: `Parent+Child`
      - [x] Compound types: pointer, array, byref: `int*[]&`
      - [x] Generic type specs: ``List`1+Enumerator[int]``
  - [x] Materializer (convert ASTs into IR instructions)
  - **Missing instructions**
    - [x] StoreArray (syntax: may need annotation for element type)
    - [x] Convert
    - [ ] Switch (parsing)
    - [ ] Intrinsics (see #5)
    - [ ] Guard (parsing), Leave/Continue
    - [x] Load/Store PtrInst (syntax: may need annotation for element type)
    - [x] NewObj
    - _and others_
- [ ] Find a way to prevent conflicts with anonymous/sequential names (enforce correctness _or_ don't put them in the SymbolTable?)
- [x] Support for multiple error messages (don't throw exceptions unless necessary)
  - [ ] Find a way to prevent cascade errors (maybe skip to the next line?)
- [x] Single pass parser (get rid of the AST/materializer and create IR directly)
- [x] Method declarations
- [?] Type declarations

### Known Bugs
  - [ ] Block order is not preserved during materialization (lazy calls to CreateBlock())

**Comment by dubiousconst282** [comment]
Closing since the parser is quite complete and implementing missing instructions shouldn't be too complicated.
